export type Category = {
    slug: string;
    label: string;
    apiValue: string;
    description: string
};
  
export const categories: Category[] = [
    { slug: "flexi-cap", label: "Flexi Cap", apiValue: "Flexi", description:
        "Flexi Cap Funds are diversified equity mutual funds that invest across large-cap, mid-cap, and small-cap stocks without any fixed allocation restriction. The fund manager has complete flexibility to dynamically adjust exposure depending on market conditions, valuations, and growth opportunities. During uncertain markets, the fund may increase allocation to stable large-cap companies, while in bullish phases it may allocate more toward mid and small caps for higher growth potential. This flexibility helps in managing risk while capturing upside opportunities. Flexi Cap funds are suitable for investors seeking long-term capital appreciation with diversification across market capitalizations in a single portfolio." },
    { slug: "large-cap", label: "Large Cap", apiValue: "Large", description:
        "Large Cap Funds primarily invest in the top 100 companies based on market capitalization. These companies are typically well-established businesses with stable earnings, strong management, and proven track records. Because they operate at scale and are leaders in their respective industries, large-cap stocks generally experience lower volatility compared to mid and small caps. While growth potential may be relatively moderate, they provide stability and consistency during market downturns. Large Cap funds are ideal for conservative equity investors who want exposure to the stock market but prefer relatively lower risk and steady long-term wealth creation." },
    { slug: "mid-cap", label: "Mid Cap", apiValue: "Mid", description:
        "Mid Cap Funds invest in companies ranked between 101 and 250 by market capitalization. These companies are often in a growth phase and have the potential to become future industry leaders. Mid-cap stocks typically offer a balance between growth and risk — higher growth potential than large caps but lower risk compared to small caps. However, they can be more volatile during market fluctuations. Mid Cap funds are suitable for investors with a moderate to high risk appetite who are looking for higher long-term capital appreciation and are comfortable with short-term market volatility." },
    { slug: "small-cap", label: "Small Cap", apiValue: "Small", description:
        "Small Cap Funds invest in companies ranked beyond the top 250 in terms of market capitalization. These companies are usually emerging businesses with significant growth potential but may carry higher business and market risks. Small-cap stocks tend to be more volatile and can experience sharp price movements during market cycles. However, over the long term, they have the potential to generate substantial returns if the businesses succeed and scale effectively. Small Cap funds are best suited for aggressive investors with a long investment horizon who can tolerate higher volatility in pursuit of superior capital appreciation." },
    { slug: "multi-cap", label: "Multi Cap", apiValue: "Multi", description:
        "Multi Cap Funds are diversified equity funds that invest in large-cap, mid-cap, and small-cap stocks with a mandatory minimum allocation to each segment. This structure ensures balanced exposure across market capitalizations, reducing concentration risk. Unlike Flexi Cap funds, Multi Cap funds must maintain specific allocations, which enforces disciplined diversification. These funds aim to capture growth opportunities from smaller companies while maintaining stability through large-cap exposure. Multi Cap funds are suitable for investors seeking a well-diversified portfolio within a single fund and who want exposure to the entire equity market spectrum for long-term wealth creation." },
    { slug: "focused", label: "Focused Fund", apiValue: "Focused", description:
        "Focused Funds are equity mutual funds that invest in a concentrated portfolio of up to 30 stocks. Unlike diversified funds that spread investments across many companies, focused funds aim to generate higher returns by taking high-conviction bets on a limited number of carefully selected stocks. Because of this concentrated strategy, performance heavily depends on the fund manager's stock selection ability. While this approach can deliver strong outperformance when selections work well, it may also increase volatility and downside risk. Focused funds are suitable for investors with a high risk appetite who believe in active management and are comfortable with a concentrated equity strategy." },
    { slug: "sectoral", label: "Sectoral / Thematic", apiValue: "Sectoral", description:
        "Sectoral and Thematic Funds invest primarily in specific sectors such as banking, technology, infrastructure, or pharmaceuticals, or follow broader themes like consumption, ESG, or manufacturing. These funds aim to capitalize on growth trends within a particular industry or economic theme. While they can generate high returns during favorable sector cycles, they carry higher risk due to limited diversification. If the chosen sector underperforms, the fund’s returns may be significantly impacted. Sectoral funds are best suited for experienced investors who understand market cycles and want to take tactical exposure to specific industries for potential high growth." },
    { slug: "value", label: "Value Fund", apiValue: "Value", description:
        "Value Funds follow a value investing strategy by identifying fundamentally strong companies that are currently undervalued by the market. These stocks may be trading at lower price-to-earnings or price-to-book ratios due to temporary challenges or negative sentiment. The fund manager aims to invest in such companies before the broader market recognizes their true worth. Value investing requires patience, as returns may take time to materialize. However, this approach can offer attractive risk-adjusted returns over the long term. Value Funds are suitable for investors who prefer disciplined investing strategies and are willing to stay invested for extended periods." },
    { slug: "contra", label: "Contra Fund", apiValue: "Contra", description:
        "Contra Funds adopt a contrarian investment strategy by going against prevailing market trends and sentiments. The fund manager invests in stocks or sectors that are currently unpopular or undervalued but have strong long-term fundamentals. The philosophy behind this strategy is that markets often overreact to short-term events, creating opportunities to buy quality businesses at attractive valuations. While contra investing can generate significant returns when market sentiment reverses, it requires patience and a high tolerance for temporary underperformance. Contra Funds are suitable for long-term investors who understand cyclical market behavior and are comfortable with contrarian strategies." },
    { slug: "elss", label: "ELSS", apiValue: "ELSS", description:
        "Equity Linked Savings Schemes (ELSS) are diversified equity mutual funds that offer tax benefits under Section 80C of the Income Tax Act. Investments up to the prescribed limit qualify for tax deduction, making ELSS one of the most popular tax-saving investment options. These funds come with a mandatory three-year lock-in period, which is the shortest among tax-saving instruments under Section 80C. ELSS funds primarily invest in equities, aiming for long-term capital appreciation. They are suitable for investors looking to save taxes while participating in equity market growth, provided they can remain invested for at least three years." },
    { slug: "liquid", label: "Liquid Fund", apiValue: "Liquid", description:
        "Liquid Funds invest in short-term money market instruments such as treasury bills, commercial papers, and certificates of deposit with maturities up to 91 days. These funds aim to provide high liquidity with relatively low risk compared to other debt funds. They are commonly used for parking surplus cash for short durations while earning better returns than traditional savings accounts. Liquid funds carry minimal interest rate risk due to their short maturity profile. They are suitable for investors seeking capital preservation, easy access to funds, and short-term investment options ranging from a few days to a few months." },
    { slug: "overnight", label: "Overnight Fund", apiValue: "Overnight", description:
        "Overnight Funds invest in securities with a maturity of just one day, making them one of the safest categories within debt mutual funds. Because the portfolio resets daily, these funds carry virtually no interest rate risk or credit duration risk. Returns are generally modest but stable, closely aligned with short-term money market rates. Overnight funds are ideal for extremely short-term parking of funds, such as for a few days, while ensuring minimal risk to capital. They are suitable for conservative investors or institutions looking for a secure alternative to keeping idle cash in bank accounts." },
    { slug: "money-market", label: "Money Market", apiValue: "Money Market", description:
        "Money Market Funds invest in short-term debt instruments such as treasury bills, commercial papers, certificates of deposit, and other money market securities with relatively short maturities. These funds aim to provide liquidity and relatively stable returns while maintaining low risk compared to longer-duration debt funds. They are slightly more flexible than liquid funds in terms of maturity profile but still focus on high-quality instruments. Money Market funds are suitable for investors looking to park funds for short durations, typically ranging from a few months to a year, while earning better returns than savings accounts with moderate safety." },
    { slug: "floater", label: "Floater Fund", apiValue: "Floater Fund", description:
        "Floater Funds invest primarily in debt instruments that carry floating interest rates, meaning their coupon payments adjust periodically based on benchmark rates. This structure helps reduce interest rate risk when rates are rising, as returns can adjust upward with changing market conditions. These funds are particularly useful in rising interest rate environments where fixed-rate bonds may suffer price declines. While they still carry credit risk depending on the quality of underlying securities, they are relatively less sensitive to duration risk. Floater funds are suitable for investors seeking debt exposure with reduced sensitivity to interest rate fluctuations." },
    { slug: "low-duration", label: "Low Duration Fund", apiValue: "Low Duration Fund", description:
        "Low Duration Funds invest in debt and money market instruments with an average portfolio duration between six and twelve months. They aim to strike a balance between generating slightly higher returns than liquid funds and maintaining relatively low interest rate risk. Because of their short maturity profile, these funds experience limited volatility compared to longer-duration debt funds. Low Duration funds are suitable for investors with a short-term investment horizon of six months to one year who seek better returns than traditional savings instruments while keeping risk moderate." },
    { slug: "short-duration", label: "Short Duration Fund", apiValue: "Short Duration Fund", description:
        "Short Duration Funds invest in debt securities with an average maturity ranging from one to three years. These funds offer a balance between risk and return by maintaining moderate exposure to interest rate movements. While they are slightly more sensitive to rate changes compared to low-duration funds, they typically provide better yield potential over the medium term. Short Duration funds are suitable for investors with an investment horizon of one to three years who want relatively stable returns with moderate interest rate risk." },
    { slug: "medium-duration", label: "Medium Duration Fund", apiValue: "Medium Duration Fund", description:
        "Medium Duration Funds invest in debt instruments with an average portfolio duration of three to four years. Because of the longer maturity profile, these funds are more sensitive to interest rate movements compared to short-term debt funds. They can benefit significantly during falling interest rate cycles but may experience temporary volatility when rates rise. Medium Duration funds are suitable for investors with a medium-term investment horizon who understand interest rate cycles and are comfortable with moderate volatility in pursuit of potentially higher returns." },
    { slug: "corporate-bond", label: "Corporate Bond", apiValue: "Corporate Bond", description:
        "Corporate Bond Funds primarily invest in high-rated corporate debt securities. By focusing on instruments with strong credit ratings, these funds aim to reduce credit risk while generating stable income. The portfolio typically consists of bonds issued by financially sound companies. While they may still face interest rate risk depending on duration, credit quality is generally maintained at a high standard. Corporate Bond funds are suitable for conservative investors seeking predictable income and relatively lower credit risk within the debt mutual fund category." },
    { slug: "credit-risk", label: "Credit Risk", apiValue: "Credit Risk", description:
        "Credit Risk Funds invest predominantly in lower-rated corporate bonds with the objective of earning higher yields. Since these bonds carry relatively higher credit risk, they offer better interest rates compared to highly rated securities. The fund manager aims to identify companies with improving credit profiles to capture potential upside. However, these funds can experience volatility if issuers face financial stress or default risk. Credit Risk funds are suitable for investors with higher risk tolerance who understand credit dynamics and seek enhanced income potential from debt investments." },
    { slug: "aggressive-hybrid", label: "Aggressive Hybrid", apiValue: "Aggressive", description:
        "Aggressive Hybrid Funds invest predominantly in equities, typically allocating 65% to 80% of their portfolio to stocks, with the remainder invested in debt instruments. This structure allows investors to benefit from equity market growth while maintaining some stability through debt allocation. These funds aim to deliver higher long-term returns compared to conservative hybrid funds but may experience equity-driven volatility. Aggressive Hybrid funds are suitable for investors who want a balanced approach but still prefer a strong equity orientation for long-term wealth creation." },
    { slug: "conservative-hybrid", label: "Conservative Hybrid", apiValue: "Conservative", description:
        "Conservative Hybrid Funds allocate the majority of their portfolio to debt instruments, typically 75% to 90%, with a smaller portion invested in equities. The objective is to generate stable income while offering limited exposure to equity markets for potential growth. These funds aim to reduce volatility compared to pure equity funds while providing better return potential than pure debt funds. Conservative Hybrid funds are suitable for investors with low to moderate risk appetite who seek income stability along with limited participation in equity growth." },
    { slug: "dynamic-asset-allocation", label: "Dynamic Asset Allocation", apiValue: "Dynamic", description:
        "Dynamic Asset Allocation Funds, also known as Balanced Advantage Funds, actively adjust their allocation between equity and debt based on market valuations and economic indicators. The fund manager increases equity exposure during attractive valuations and reduces it when markets appear overheated. This dynamic strategy aims to manage downside risk while participating in market growth. These funds are suitable for investors who want equity participation with built-in risk management and prefer professional allocation decisions rather than manually timing the market." },
    { slug: "multi-asset-allocation", label: "Multi Asset Allocation", apiValue: "Multi", description:
        "Multi Asset Allocation Funds invest in at least three different asset classes such as equity, debt, and gold or other commodities. This diversified structure helps reduce overall portfolio risk by spreading investments across uncorrelated assets. When one asset class underperforms, another may compensate, leading to smoother returns over time. These funds aim to provide balanced growth with reduced volatility. Multi Asset Allocation funds are suitable for investors seeking broad diversification and a one-stop solution across multiple asset classes." },
    { slug: "equity-savings", label: "Equity Savings", apiValue: "Equity Savings", description:
        "Equity Savings Funds combine equity, arbitrage, and debt strategies to generate relatively stable returns with lower volatility than pure equity funds. The arbitrage portion helps reduce market risk by exploiting price differences between cash and derivatives markets. The debt allocation adds stability and income generation. These funds aim to provide tax-efficient returns with moderate risk. Equity Savings funds are suitable for conservative investors who want limited equity exposure while maintaining a relatively stable return profile." },
    { slug: "arbitrage", label: "Arbitrage Fund", apiValue: "Arbitrage Fund", description:
        "Arbitrage Funds aim to generate returns by exploiting price differences between cash and derivatives markets. The fund manager simultaneously buys stocks in the cash market and sells them in the futures market to capture risk-free spreads. Since positions are typically hedged, these funds carry lower equity risk compared to traditional equity funds. Returns are generally aligned with short-term interest rates. Arbitrage funds are suitable for investors seeking low-risk, tax-efficient alternatives to liquid funds, particularly during volatile market conditions." },
    { slug: "retirement", label: "Retirement Fund", apiValue: "Retirement", description:
        "Retirement Funds are solution-oriented mutual funds designed to help investors build a corpus for post-retirement needs. These funds often have a lock-in period of five years or until retirement age, whichever is earlier. They may invest in a mix of equities and debt depending on the fund’s strategy and target age profile. The objective is long-term capital growth combined with risk management as retirement approaches. Retirement funds are suitable for individuals planning systematically for financial independence in their later years." },
    { slug: "children", label: "Children's Fund", apiValue: "Children", description:
        "Children's Funds are solution-oriented mutual funds created to meet long-term financial goals related to a child's education, marriage, or future needs. These funds typically have a lock-in period of at least five years or until the child reaches a certain age. They may invest in equity for growth and debt for stability, depending on the strategy. The long investment horizon allows compounding benefits over time. Children's funds are suitable for parents seeking disciplined, goal-based investing for their child's future." },
    { slug: "fund-of-funds", label: "Fund of Funds", apiValue: "Fund of Funds", description:
        "Fund of Funds (FoF) invest in other mutual fund schemes instead of directly investing in stocks or bonds. This structure allows investors to gain diversified exposure across multiple funds or even international markets through a single investment. The performance depends on the underlying funds’ strategies and asset allocation. While FoFs provide diversification benefits, they may have slightly higher expense ratios due to layered costs. Fund of Funds are suitable for investors seeking simplified diversification across asset classes or geographies." },
    { slug: "index", label: "Index Fund", apiValue: "Index", description:
        "Index Funds are passive mutual funds designed to replicate the performance of a specific market index such as Nifty 50 or Sensex. Instead of actively selecting stocks, the fund mirrors the index composition and weightage. Because of this passive strategy, index funds typically have lower expense ratios compared to actively managed funds. They aim to deliver returns closely aligned with the benchmark index. Index funds are suitable for investors who prefer low-cost, transparent investing and believe in long-term market growth without relying on active stock selection." },
    { slug: "etf", label: "ETF", apiValue: "ETF", description:
        "Exchange Traded Funds (ETFs) are marketable securities that track an index, commodity, or basket of assets and trade on stock exchanges like regular shares. ETFs combine features of mutual funds and stocks, offering diversification along with real-time trading flexibility. They usually have lower expense ratios due to their passive management style. Investors can buy and sell ETFs during market hours at prevailing prices. ETFs are suitable for cost-conscious investors seeking transparent, liquid, and diversified exposure to specific indices, sectors, or asset classes." },
];
  
export function getCategoryBySlug(slug: string) {
    return categories.find((cat) => cat.slug === slug);
}