import type { Metadata } from "next";
import TopLoader from "../TopLoader";
import { Footer } from "../ui/components/Footer";
import { Header } from "../ui/components/Header";

export const metadata: Metadata = {
    title: "About Us",
    description: "Generated by create next app",
};

export default function AmcLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        <TopLoader />
        <Header />
        {children}
        <Footer />
    </>
  );
}
